### ISSUE TITLE
Available Energy showing unknown and health showing 100%, but all other values are correct

### ISSUE THREAD

**Issue by Ashpork** [WillCodeForCats/solaredge-modbus-multi#211]
Before reporting a bug, make sure your configuration is correct and your LAN is working.
https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Configuration

Do not ask for setup help: setup is not a "bug". Post help requests in one of the community support options.

**Describe the bug**
I installed v2.2.7 last week and the storage controls (thank you!). Yesterday at 15:30 the state of health jumped from 95% to 100% and "available energy" has since shown "unknown. 

I have a SE Inverter (SE5000H-RW000BNN4) and SE Energy Bank.

No Versions changed on both Inverter and Battery during this time.

**Expected behavior**
State of health should show a value.

**Screenshots**
![image](https://user-images.githubusercontent.com/70691313/206668509-46603550-6954-4b59-9fa7-ac70d1ee8da8.png)

**Logs**
[SE.log](https://github.com/WillCodeForCats/solaredge-modbus-multi/files/10193512/SE.log)

**Home Assistant (please complete the following information):**
 - Home Assistant Core Version: 2022.12.0
 - solaredge-modbus-multi Version: v2.2.7

**Additional context**

**Comment by WillCodeForCats** [comment]
The display is correct, the issue is with the inverter or battery not sending data properly.

Example:
2022-12-08 15:36:32.389 DEBUG Inverter 1 batt 1: B_Energy_Available 0x461a08f6
2022-12-08 15:36:34.388 DEBUG Inverter 1 batt 1: B_Energy_Available 0x461a08f6
2022-12-08 15:36:50.845 DEBUG Inverter 1 batt 1: B_Energy_Available 0x461a08f6
2022-12-08 15:37:05.786 DEBUG Inverter 1 batt 1: B_Energy_Available 0x461a08f6

Every update returned value "0x461a08f6" which is being displayed correctly in the integration.

Other users that have reported that they needed to power cycle their inverter, battery, or both.

**Comment by WillCodeForCats** [comment]
The reason that is displaying as "unknown" is because the battery is reporting it has a rated energy of 0x46179000 (9700) but the reported energy available 0x461a08f6 (9858.24) is higher than the rated energy. Available and max energy values should not be higher than rated energy. Rated energy is the "nameplate" size of the battery.

**Comment by WillCodeForCats** [comment]
State of Heath is showing 100% because that's the value the inverter gave us: B_SOH 0x42c80000 (100). The integration will display what the value was reported, nothing to interpret about this one.
