### ISSUE TITLE
After Update 06.08.2023: Detects 2nd battery where there is none

### ISSUE THREAD

**Issue by Ojoachim71** [WillCodeForCats/solaredge-modbus-multi#385]
Hello! Sine today (since Update), a second battery device shows up (B2). All values of this are unknown or empty. B1 works as expected.

It should only detect one battery, like in the release before, where there is only one.

Nothing else was changed, plugin accesses data from evcc modbus proxy.

Its's not possible to deleted 2nd device battery B2.

Regards,
Oliver

**Comment by masterx1981** [comment]
I have freshly installed the integration, and the first time has detected 1 inverter and 2 meters and no battery, after a reinstall got 1 inverter, 1 meter but still no battery... maybe something wrong with detection

**Comment by WillCodeForCats** [comment]
Please resubmit with all of the requested information in the template: there is no information here for me to work with.

**Comment by deqw** [comment]
> Please resubmit with all of the requested information in the template: there is no information here for me to work with.

Hi Seth @WillCodeForCats. I think there isn't much more to add. After the v2.4.0 update a 2nd battery device is added to the configuration while that battery does not exist. This B2 device cannot be deleted from the integration and all information/sensors with this device is unknown.

**Comment by Ojoachim71** [comment]
👍

**Comment by WillCodeForCats** [comment]
There is an entire bug report template that was ignored with a big warning at the top not to delete it. I ask for all that information for a reason. I cannot help without it. I hate wasting my time asking for basic information the template asks for before starting. Opening an issue and deleting the template because why? Why would anyone open a ticket and think I don't think I need all the information I ask for?

If someone wants to actually help me go open a new bug report and see what the template asks for:

https://github.com/WillCodeForCats/solaredge-modbus-multi/issues/new/choose

**Comment by deqw** [comment]
Yep saw the template, I had already started there this morning and halfway the template I'd quit (and found later this already closed topic) because all is asked isn't necessary to point you to a minor problem that was introduced with v2.4.0. But we'll now patiently have to wait for someone to do the entire template.

**Comment by WillCodeForCats** [comment]
I don't have access to batteries, I have no way to see what could even possibly be the problem.

**Comment by deqw** [comment]
I understand Seth, that is not very convenient for development. I have no development environment setup myself so I can't help you with that, but if you can think of any other information I can provide you with, beside the template of course ;o) I'll be glad to help. The B2 isn't in the way otherwise so it isn't a big problem.

**Comment by WillCodeForCats** [comment]
[Release v2.4.2-pre.2](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.4.2-pre.2)
