### ISSUE TITLE
Inverter overreporting AC energy

### ISSUE THREAD

**Issue by 12koen** [WillCodeForCats/solaredge-modbus-multi#444]
**Describe the feature**
The AC energy reported by the inverter is overstated by 3.3%. I resolved it by adding a sensor that integrates the AC power into AC energy. 

Due to the overreporting the energy dashboard shows a higher home electricity use and higher direct use of solar energy.

**Screenshots**
![image](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/124468635/4e2b69c4-4f65-472f-adf5-bca3973d9bbd)
3 hour period at maxed out production 8840.8 to 8856.3 kWh gives 15.5 kWh in 3 hours whereas the maximum production of the inverter is only 5kW

**Home Assistant (please complete the following information):**
 - Home Assistant Core Version:  2023.9.1
 - solaredge-modbus-multi Version: 2.4.5
 - Inverter: SE5000H HD-Wave

**Additional context**
Add any other context about the request here.

**Comment by WillCodeForCats** [comment]
The integration should only report the data given by the inverter, not manipulate it.

Adding a revenue grade meter with C0.6 current transformers is the typical solution, where the equipment is designed for high accuracy measurements. As far as I understand the inverter is not revenue grade on its own so inaccuracies should be expected without revenue grade metering.

Otherwise if you used a template sensor you can post your code to discussions and it's up to the user to determine if they want to alter sensor data.
