### ISSUE TITLE
Battery Energy Import unavailable

### ISSUE THREAD

**Issue by Pippowicz** [WillCodeForCats/solaredge-modbus-multi#499]
### Describe the bug

Most of the Time the Entity Energy Import for the Battery is unavailable, is that normal?

Inverter SE10K-RWB48, Firmware 0004.0019.0036, Solaredge Home Battery 13,8 KWh

### Expected behavior

Entity should show Value as Energy Export Entity

### Screenshots

![image](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/74784562/69d7dd22-fe4e-422d-9093-7b225826a34c)

### Diagnostic File

[diag.json.txt](https://github.com/WillCodeForCats/solaredge-modbus-multi/files/13893770/diag.json.txt)

### Home Assistant Version

2024.1.1

### solaredge-modbus-multi Version

2.4.8

### Installation Type

HAOS

### Read the Instructions

- [X] I have read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki
- [X] My configuration follows https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Configuration
- [X] This issue is not about a template error (template errors should not be reported as an issue, read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Template-Design-Notes)

**Comment by WillCodeForCats** [comment]
In the diagnostic file your battery import value is 0 which will show as unavailable. I use the SunSpec definitions where 0 means "Not Accumulated" so this is correct.

If you have a battery that resets energy counters this is a known issue and you can turn on the Allow Battery Energy Reset option to work around it. Otherwise when the counter resets it will stay in unavailable state since in Home Assistant the total incrementing sensor value should never go backwards.

https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Known-Issues

**Comment by Pippowicz** [comment]
Hi Will, 

i am using a genuine Solaredge Battery, in the Known Issues you linked you talk only about LG or BYD Batteries. 

So i assumed setting "Allow Battery Energy to Reset" is not needed in my Case.
I will have a look tomorrow when the Sun is up if there are any Values.

If not i assume i have to Powercycle the Inverter and / or Batteries, right?

**Comment by WillCodeForCats** [comment]
I don't have batteries, so I can't say personally what would be the solution if it's not already written down.

I would try the option anyway, you can always turn it off again.

**Comment by Pippowicz** [comment]
Hi and Sorry for the late Response. It seems the Entity comes available when there is Sunlight AND the Batteries are 
charging. So this was not an Issue - i just misunderstood the function.
